### PR TITLE
add auto reconnect when scanner is disconnected

### PR DESCRIPTION
**Pull request by mateuszcierpikowski**
Hi, 
I have a problem with disconnecting Sick S300 scanner. I noticed that your driver doesn't reconnect automatically when USB converter is detected by system again. So I added auto-reconnect feature.

### CODE REVIEW

**Comment by ipa-rmb** [comment]
@ipa-jba @ipa-owner-fez Can someone from the navigation team approve the addon?

**Comment by fmessmer** [comment]
we never experienced disconnecting scanners...so I'm a bit anxious about adding something to this driver that we haven't missed so far..definitely needs to be well-tested on our platforms!
what's your setup? do you have lose cables?
do you use proper udev rules to map the scanners to specific `/dev/...` files so they do not change ar runtime...
I'd rather investigate why your scanners disconnect than adding a re-connect workaround

**Comment by mateuszcierpikowski** [comment]
udev rules are configured properly. It's a problem with loose USB contacts. Sometimes scanners disconnect only for a second. After that scanner is properly detected by system but your driver doesn't publish scan data... You can test it if you detach scanner and connect it again.

**Comment by fmessmer** [comment]
I'll try to find a slot to test this...a little patience please :wink:

**Comment by fmessmer** [comment]
I had a quick look at this PR this morning

`indigo_dev`-behavior:
 - scanners plugged in, valid udev rules, start driver, scans published, diagnostics OK
 - unplug scanners, driver goes to "simulation mode", no scans published, diagnostics STALE
 - re-plug scanners, valid udev rules, driver stays in "simulation mode", no scans, diagnostics STALE

`feature/auto_reconnect`-behavior:
 - scanners plugged in, valid udev rules, start driver, scans published, diagnostics OK
 - unplug scanners, driver tries to re-connect, no scans, diagnostics ERROR (scanner not on port)
 - re-plug scanners, valid udev rules, scans published again, diagnostics OK again

thus, I'd say this PR is definitely an improvement

however, the part "re-plug scanners, valid udev rules", does not yet work for us that straight-forward:
we are using symlinked devices instead of fixed udev rules...thus, wen unplugging the scanners, those links become invalid....and do not become valid again after re-plugging the scanners....to make them valid again, our [udev script](https://github.com/mojin-robotics/cob_hardware_test/blob/indigo_dev/cob_devices_test/scripts/udev_s300.sh) has be executed once again....
I'd say, this is a problem on our side and we should modify our udev handling for the scanners...see mojin-robotics/setup_cob4#73


what's the opinion of the other maintainers here?
@ipa-fez @ipa-jba @ipa-rmb @floweisshardt @benmaidel

**Comment by floweisshardt** [comment]
I'm ok with merging as the behavior doesn't change for us (we're typically not unplugging the scanners during operation!)

**Comment by ipa-rmb** [comment]
I agree with @floweisshardt . The PR improves the stability of the driver in general while not making it worse for our robots which would have a problem either way after losing connection.

**Comment by fmessmer** [comment]
thanks @mateuszcierpikowski

**Pull request merged**
