### PR TITLE
smooth voltage calculation

### PR DESCRIPTION
**Pull request by benmaidel**
smooth calculated voltage from phidget board by adapting average over windows of measurements

alternative method could be an outlier detection.

### CODE REVIEW

**Comment by benmaidel** [comment]
@ipa-fmw was this new behavior satisfying?

**Comment by floweisshardt** [comment]
I didn't have the chance to verify this on hardware yet

**Comment by benmaidel** [comment]
Because cob4 switched back to bms driver we could test this on raw3.
@ipa-flg, @ipa-jba Perhaps you find some time during your upcoming demonstrations to test this?

**Comment by jabbenseth** [comment]
We tested it on raw3-3. with https://github.com/ipa320/cob_robots/issues/623 the voltage seems nicer (compared to indigo_dev with rqt_plot) but not too smooth :+1: from my site.

**Review by jabbenseth — APPROVED** [review]

**Comment by fmessmer** [comment]
@ipa-jba 
Do you have a before/after-screenshot?

@ipa-bnm 
Have you seen the behavior? In case you approve @ipa-jba's test on raw3-3, please merge!

**Comment by benmaidel** [comment]
@ipa-fxm 
Nope, I have not seen the behavior. For a clean merge I need to have at least one approved review from someone with write access to this repo.

**Review by fmessmer — APPROVED** [review]
I can give the (code) approval...still I'd suggest to let @ipa-bnm merge this PR after he has verified/seen/tested the behavior on the robot....

**Pull request merged**
