### PR TITLE
test noetic

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by fmessmer** [comment]
needs https://github.com/ros/rosdistro/pull/26767

**Comment by fmessmer** [comment]
@ipa-rmb @ipa-jcl @ipa-fog @ipa-foj (and all other perception guys at IPA)
@ipa-fez @ipa-owner-fez @ipa-jba @ipa-owner-jba 

as discussed in https://github.com/ipa320/cob_perception_common/pull/101#issuecomment-702733793, I will remove `cob_camera_sensors` from this repo (it will still be available in older tags though)

**Comment by ipa-fez** [comment]
Looks like numpy also needs a conditional include for python3. Otherwise looks good to me.

**Review by ipa-fez — DISMISSED** [review]

**Comment by mathias-luedtke** [comment]
@fmessmer: Are we still using python2 for noetic? This might download a lot of packages..

**Comment by mathias-luedtke** [comment]
run_travis:

image

**Comment by mathias-luedtke** [comment]
Workaround for now: ` AFTER_INIT="echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"`

**Comment by mathias-luedtke** [comment]
> Workaround for now: ` AFTER_INIT="echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"`

Or ` BEFORE_INIT_EMBED="export DEBIAN_FRONTEND=noninteractive"`
I will make this a permanent setting (https://github.com/ros-industrial/industrial_ci/pull/564)

**Comment by fmessmer** [comment]
@ipa-mdl your fix for `industrial_ci` seems to work: noetic job now finishes in <10 mins as kinetic/melodic job
Thanks!

I'll wait for the fix to get merged and then revert the `tmp` commit in this PR

**Pull request merged**
