### PR TITLE
bugfix infinit-send-error

### LINKED ISSUE #187: cob_light: infinity-loop with output "Error sending stageprofi"
very sporadic error and not permanently reproducible.
because ros didn't wrote the log, the console-output "Error sending stageprofi" are all i have.

### PR DESCRIPTION
**Pull request by benmaidel**
Should fix #187. This is untested!

### CODE REVIEW

**Comment by floweisshardt** [comment]
testing on cob4-2: Failed (for torso and base LEDs)

ERROR_LOG for torso (similar for base):

roslaunch cob_bringup light.launch component_name:=light_torso
... logging to /u/fmw/.ros/log/7c63d3e4-8060-11e4-88b8-eca86bff61c1/roslaunch-cob4-2-t2-6571.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cob4-2-t2:53208/

# SUMMARY

PARAMETERS
- /light_torso/baudrate: 38400
- /light_torso/devicedriver: stageprofi
- /light_torso/devicestring: /dev/ttyLED
- /light_torso/invert_output: False
- /light_torso/num_leds: 58
- /light_torso/pubmarker: True
- /light_torso/sim_enabled: False
- /light_torso/startup_color: [0.0, 1.0, 0.7, 0.4]
- /light_torso/startup_mode: Breath
- /rosdistro: indigo
- /rosversion: 1.11.9

NODES
  /
    light_torso (cob_light/cob_light)

ROS_MASTER_URI=http://cob4-2-b1:11311

core service [/rosout] found
process[light_torso-1]: started with pid [6582]
[ INFO] [1418221020.349045277]: Open Port on /dev/ttyLED
[ INFO] [1418221020.349721087]: Serial connection on /dev/ttyLED succeeded.
[ERROR] [1418221020.350049007]: Initializing connection to driver failed. Exiting
[light_torso-1] process has finished cleanly
log file: /u/fmw/.ros/log/7c63d3e4-8060-11e4-88b8-eca86bff61c1/light_torso-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by floweisshardt** [comment]
@ipa-bnm: can you get back on this?

**Comment by benmaidel** [comment]
i think i fixed it. Should be tested

**Comment by benmaidel** [comment]
test on cob4-2 succeed!

roslaunch cob_bringup light.launch robot:=cob4-2 component_name:=light_torso
... logging to /u/bnm/.ros/log/4168acf4-a30d-11e4-b3cc-eca86bff61c1/roslaunch-cob4-2-t1-26590.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cob4-2-t1:56659/

# SUMMARY

PARAMETERS
- /light_torso/baudrate: 38400
- /light_torso/devicedriver: stageprofi
- /light_torso/devicestring: /dev/ttyLED
- /light_torso/invert_output: False
- /light_torso/num_leds: 58
- /light_torso/pubmarker: True
- /light_torso/sim_enabled: False
- /light_torso/startup_color: [0.0, 1.0, 0.7, 0.4]
- /light_torso/startup_mode: Breath
- /rosdistro: indigo
- /rosversion: 1.11.10

NODES
  /
    light_torso (cob_light/cob_light)

ROS_MASTER_URI=http://cob4-2-b1:11311

core service [/rosout] found
process[light_torso-1]: started with pid [26624]
[ INFO] [1422026302.545325264]: Open Port on /dev/ttyLED
[ INFO] [1422026302.545793957]: Serial connection on /dev/ttyLED succeeded.
[ INFO] [1422026302.546454553]: Executing new mode: BreathMode
^C[light_torso-1] killing on exit
stopping mode
[ INFO] [1422026327.486553577]: Mode BreathMode finished
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by floweisshardt** [comment]
thanks

**Pull request merged**
