### PR TITLE
[sound, light] fix diagnostics

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by fmessmer** [comment]
The whole `main()` looks somewhat strange!
Especially [this part](https://github.com/ipa-cob4-2/cob_driver/blob/indigo_dev/cob_sound/ros/src/sound.cpp#L135-L140)
The main only instantiates an object of the `Say` class and then spins....
for publishing diagnostics we could create a ros::Timer and put the code for publishing into the timer_cb function....

**Comment by floweisshardt** [comment]
+1
that's a todo for next wednesday

**Comment by floweisshardt** [comment]
tested on cob4-2: OK

**Comment by fmessmer** [comment]
fine with me

**Pull request merged**
