### PR TITLE
install_tags

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by fmessmer** [comment]
this PR supersedes #114

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by floweisshardt** [comment]
waiting for answer of @ipa-jsf to delete everything in cob_camera_sensors except the set_camera_info.py script

**Comment by fmessmer** [comment]
removed files as discussed with @ipa-jsf and @ipa-rmb

@ipa-fmw 
PullRequest complete!

**Comment by floweisshardt** [comment]
visual review: OK

**Pull request merged**
