### PR TITLE
send em_state only if data from phidget received

### PR DESCRIPTION
**Pull request by benmaidel**

### CODE REVIEW

**Comment by benmaidel** [comment]
tested with @ipa-flg on raw3-3

**Comment by ipa-flg** [comment]
successfully tested on raw3-3

**Comment by ipa-flg** [comment]
@ipa-bnm ;-)

**Review by ipa-flg — APPROVED** [review]

**Comment by ipa-flg** [comment]
nice try ;-)

**Review by fmessmer — APPROVED** [review]
as discussed with @ipa-bnm

**Pull request merged**
