### PR TITLE
[cob_sick_s300] Added private node handle for parameters.

### PR DESCRIPTION
**Pull request by tonybaltovski**
Added a private node handle for parameters to allow for multiple lasers to be used.

### CODE REVIEW

**Comment by fmessmer** [comment]
While I see the use-case, merging this would require us to reconsider our current configuration in https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_hardware_config/cob4-2/config/base_laser_left.yaml and the launch file https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/sick_s300.launch because currently we also have the laser filter params in the same yaml....

**Comment by tonybaltovski** [comment]
I will follow suite and use the group namespace.  I thought it was a overlooked as the private node handle was commented out [here](https://github.com/ipa320/cob_driver/blob/indigo_dev/cob_sick_s300/ros/src/cob_sick_s300.cpp#L121).

**Comment by fmessmer** [comment]
So, I'll close this PR unmerged....

**Comment by mgruhler** [comment]
I know, I'm quite late to the party. But thanks @tonybaltovski this has bothered me for quite a while as well.

I'm not quite sure if, or if yes, when, we'll tackle this. This is on my list as well, but doe to the configuration issues I haven't fixed it yet...

**Comment by tonybaltovski** [comment]
@ipa-mig No worries.  If you do change it, let me know.  Maybe, it could be considered for kinetic?

**Pull request closed without merging**
