### PR TITLE
minor change for publishing a realistic voltage value

### PR DESCRIPTION
**Pull request by souravran**

### CODE REVIEW

**Review by fmessmer — COMMENTED** [review]
do we want some fluctuation on the current, too?

**Comment by souravran** [comment]
we can introduce a fluctuation in current too in order to have a realistic time_remaining value in power_state

**Review by fmessmer — COMMENTED** [review]
@souravran 
I made some minor changes/fixed typos.
Could you test this one last time and report :+1:/:-1: : before I merge, please

**Comment by souravran** [comment]
Pulled the changes and tested the simulation, works fine !

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
