### PR TITLE
Omni wheel and yaml adaptations

### PR DESCRIPTION
**Pull request by olgen2013**
The undercarriage_control_new ros-node uses the new undercarriage_control_geom class from cob_control. Furthermore the required config for undercarriage_control_geom will be loeaded from a new yaml-config-file which was added to cob_robot.  

Maybe it would be better to create a the same branch on ipa320/cob_driver because this adapataions in undercarriage_control_new require some more and detailed tests. 

These adapatations were arranged with @ipa-mig and @ipa-mdl

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
- cob_undercarriage_ctrl/ros/src/cob_undercarriage_ctrl.cpp and cob_base_drive_chain/ros/src/cob_base_drive_chain.cpp should not be touched at all
- yaml-cpp is not needed anymore, should be removed from code and dependencies
- parameter names are hard-coded, including namespaces and node name, please use:

``` c++
// NodeHange n refers to namespace (currently /base_controller)
ros::NodeHandle nh_priv("~"); // parameter are uploaded to private space

// n.getParam("/base_controller/undercarriage_ctrl_node_new/SteerCtrl/VirtMass", param.dVirtM);
nh_priv.getParam("SteerCtrl/VirtMass", param.dVirtM);
```

However, tested on jacked raw3-1.

**Comment by mathias-luedtke** [comment]
This PR should be reissued after https://github.com/ipa320/cob_control/pull/24 was merged.
To do:
- clean-up
- migrate to new format
- (migrate to OdometryTracker)

**Comment by mgruhler** [comment]
@ipa-mdl :+1: to all the points in your first comment. 
So I suggest to leave this PR open, until cob_control#24 has been merged and reiterate then on this one.

**Comment by mgruhler** [comment]
@ipa-mdl @ipa-fmw @olgen2013 
This PR will not be merged.
New node will be put into ipa320/cob_control/cob_omni_drive_controller. In this step, the migration to the new format will be made as well.

Please keep open until this has been achieved!

**Comment by mgruhler** [comment]
New PR opened at ipa320/cob_control#28 bringing in the (adapted) changes of this PR.
This one can be closed now (@ipa-fmw)

**Pull request closed without merging**
