### PR TITLE
BMS: restart CAN interface on failure

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Might take up to 5 seconds / errors msgs to recover

### CODE REVIEW

**Comment by floweisshardt** [comment]
this should be tested on cob4-2 as soon as it is back from Ingolstadt and CAN is connected again

**Comment by mathias-luedtke** [comment]
it was tested on cob4-6 and cob4-?

Needs:

```
allow-hotplug can1
iface can1 can static
    bitrate 500000
    pre-up ip link set $IFACE type can restart-ms 10
```

in `/etc/network/interfaces`

**Comment by floweisshardt** [comment]
@ipa-nhg: can you please update the installation docs to include the changes needed for `/etc/network/interfaces`

**Comment by NadiaHG** [comment]
@ipa-fmw it is already documented : https://github.com/ipa320/setup_cob4/blob/master/InstallCob4.sh#L105  and updated https://github.com/ipa320/setup_cob4/pull/33

**Comment by floweisshardt** [comment]
perfect!
CR: OK

**Pull request merged**
