### PR TITLE
[light] publish continuous diagnostics

### PR DESCRIPTION
**Pull request by floweisshardt**
includes #220 
includes #221

### CODE REVIEW

**Comment by floweisshardt** [comment]
tested on cob4-2: OK

**Comment by floweisshardt** [comment]
is fixed in https://github.com/ipa320/cob_driver/pull/220

**Comment by floweisshardt** [comment]
fixes https://github.com/ipa320/cob4/issues/196

**Comment by floweisshardt** [comment]
fixes https://github.com/ipa320/cob_driver/issues/219

**Comment by fmessmer** [comment]
fine with me

**Pull request merged**
