### PR TITLE
fix frame_id for odometry

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by NadiaHG** [comment]
Visual Review : OK
Test on cob4-2: OK

**Comment by mgruhler** [comment]
:ok: however, we should occasionally make this a parameter...

**Comment by fmessmer** [comment]
Also, according to http://wiki.ros.org/tf2/Migration#Removal_of_support_for_tf_prefix frames starting with `/` will not be allowed for tf2...
Thus, we might want to start migrating whenever we stumble over s.th. lke this

**Comment by floweisshardt** [comment]
the `/` problem should be discussed together with the other issues from the multi-robot experients

**Pull request merged**
