### PR TITLE
remove faulty publish_rate mechanism

### LINKED ISSUE #372: s300 publish rate throttling does not work

### PR DESCRIPTION
**Pull request by fmessmer**
implements https://github.com/ipa320/cob_driver/pull/373#issuecomment-398704021

supersedes #373 
fixes #372

### CODE REVIEW

**Comment by fmessmer** [comment]
~~to be tested on hw~~

still produces scans at 25Hz...

**Comment by fmessmer** [comment]
@ipa-fez @ipa-rmb @kalectro @mgruhler 
any review? otherwise I'll merge later...

**Review by ipa-fez — APPROVED** [review]
Did not test in HW but looks good to me.

**Comment by mgruhler** [comment]
fine for me, though I couldn't test on HW as well.

But "fixes #372" is maybe a bit optimistic ;-)

**Comment by fmessmer** [comment]
it's a **wont**fix #372

**Comment by mgruhler** [comment]
agreed :grin:

**Comment by kalectro** [comment]
I like this solution :)

**Pull request merged**
