### PR TITLE
use new Trigger from std_srvs

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by mgruhler** [comment]
Visual Review: ok
Are there any other implications then changes in cob_command_tools regarding the base_drive_chain?

**Comment by floweisshardt** [comment]
visual review: OK
I currently don't see any other implications. Using the 'rosservice call' command line interface will still be the same.

**Comment by mgruhler** [comment]
:+1:

**Comment by floweisshardt** [comment]
can be merged now as std_srvs 1.11.1-0 is released (http://www.ros.org/debbuild/indigo.html?q=std_srvs)

**Comment by fmessmer** [comment]
resolving merge conflicts...merging now...see https://github.com/ipa320/cob_common/pull/153

**Pull request merged**
