### PR TITLE
cob_sick_lms1xx: add range configuration

### PR DESCRIPTION
**Pull request by Shin-nn**
Configuration for range added

### CODE REVIEW

**Comment by destogl** [comment]
Are you filter somewhere data based on this ranges?

**Comment by Shin-nn** [comment]
Yeah, we are changing lidars and so on and we need to keep correct ranges.

**Comment by destogl** [comment]
Ah OK, you are doing it in the node which reads data from sensor... Should it be added here for this laser scanner?

**Comment by Shin-nn** [comment]
Given the fact that it is constructional parameter of lidar, there is no other place to set this. It is definitely not correct to set it to 20. If this value is nonsense, you can delete such information from messages, right?

**Comment by destogl** [comment]
Yes, you are right

**Comment by floweisshardt** [comment]
looks good and does not change default behaviour.
CR: OK

**Comment by benmaidel** [comment]
+1

**Pull request merged**
