### PR TITLE
[cob_sick_s300] remove dead code

### PR DESCRIPTION
**Pull request by mgruhler**
compiles and works perfectly without...

### CODE REVIEW

**Review by ipa-fez — APPROVED** [review]
If it still works then this is fine, I guess.

**Comment by fmessmer** [comment]
:rofl: `brics` and `youbot`

well, still run a test on actual hardware, please

**Comment by mgruhler** [comment]
"works" as in "tested" :-)

**Review by floweisshardt — APPROVED** [review]
good catch. If this still works, good to merge

**Review by fmessmer — APPROVED** [review]

**Comment by fmessmer** [comment]
Have any more tests been performed with this feature branch? Did anything come up?
@ipa-mig feel free to merge if nothing came up..

**Comment by mgruhler** [comment]
AFAIR not. I tested it again on a scanner and all is good. Do you want some tests on other hardware?

**Comment by fmessmer** [comment]
@ipa-fmw test together with #334?

**Comment by ipa-fez** [comment]
@ipa-fxm @ipa-bja @ipa-rmb @ipa-fmw can we merge this and #334 or does it need more testing?

**Comment by ipa-rmb** [comment]
Did anyone test it with navigation on a real robot? Or does it not affect this at all? Was #334 tested meanwhile?

**Comment by floweisshardt** [comment]
not tested with any of the cob4s so far. Who can do that?

**Pull request closed without merging**
