### PR TITLE
fixed base_drive_chain's diagnostic name

### PR DESCRIPTION
**Pull request by benmaidel**
changed drive_chains diag name from `//base_controller` to `/base_controller/base_drive_chain_node`

### CODE REVIEW

**Comment by mgruhler** [comment]
LGTM

**Comment by floweisshardt** [comment]
LGTM

**Comment by NadiaHG** [comment]
Visual Review: OK

**Comment by NadiaHG** [comment]
@ipa-bnm did you test on a robot?

**Comment by benmaidel** [comment]
yes, tested it on cob4-2. When ipa320/cob_robots#337 is merged the resulting diagnostic name will be `/base/base_drive_chain_node`

**Pull request merged**
